"""Add admins_contact_info to ManufacturerProduct

Revision ID: 473b25eb60a7
Revises: ad8bd015986a
Create Date: 2024-08-15 21:04:23.206142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473b25eb60a7'
down_revision = 'ad8bd015986a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturer_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admins_contact_info', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturer_products', schema=None) as batch_op:
        batch_op.drop_column('admins_contact_info')

    # ### end Alembic commands ###
