"""Updated models

Revision ID: 546d16642ac3
Revises: fa48a60fc623
Create Date: 2024-08-02 12:24:26.978937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546d16642ac3'
down_revision = 'fa48a60fc623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('category',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('client',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('Shipping_address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('cart',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('CreateAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_cart_ClientID_client')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('order',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_order_ClientID_client')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('cartitem',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CartID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CartID'], ['cart.ID'], name=op.f('fk_cartitem_CartID_cart')),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], name=op.f('fk_cartitem_ProductID_product')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('orderdetails',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], name=op.f('fk_orderdetails_OrderID_order')),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], name=op.f('fk_orderdetails_ProductID_product')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('receipt',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('ReceiptDate', sa.DateTime(), nullable=False),
    sa.Column('Total', sa.BigInteger(), nullable=False),
    sa.Column('Payment', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_receipt_ClientID_client')),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], name=op.f('fk_receipt_OrderID_order')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('sales',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReceiptID', sa.BigInteger(), nullable=False),
    sa.Column('AdminID', sa.BigInteger(), nullable=False),
    sa.Column('TotalAmount', sa.BigInteger(), nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('Sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.ID'], name=op.f('fk_sales_AdminID_admin')),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_sales_ClientID_client')),
    sa.ForeignKeyConstraint(['ReceiptID'], ['receipt.ID'], name=op.f('fk_sales_ReceiptID_receipt')),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('Email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('Companyname', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Contactinfo', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['Username'])
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.drop_column('contact_info')
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Productname', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('productdescription', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('CategoryID', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('manufacturerID', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('ImageURL', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('supply_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_product_manufacturerID_manufacturer'), 'manufacturer', ['manufacturerID'], ['ID'])
        batch_op.create_foreign_key(batch_op.f('fk_product_CategoryID_category'), 'category', ['CategoryID'], ['ID'])
        batch_op.create_foreign_key(batch_op.f('fk_product_supply_id_supply'), 'supply', ['supply_id'], ['ID'])
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('AdminID', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('ManufacturerID', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('supply_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('quantity_ordered', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ProductID', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_supply_AdminID_admin'), 'admin', ['AdminID'], ['ID'])
        batch_op.create_foreign_key(batch_op.f('fk_supply_ProductID_product'), 'product', ['ProductID'], ['ID'])
        batch_op.create_foreign_key(batch_op.f('fk_supply_ManufacturerID_manufacturer'), 'manufacturer', ['ManufacturerID'], ['ID'])
        batch_op.drop_column('id')
        batch_op.drop_column('product_id')
        batch_op.drop_column('manufacturer_id')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('supply_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('ProductID', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('orderDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_supply_order_ProductID_product'), 'product', ['ProductID'], ['ID'])
        batch_op.drop_column('id')
        batch_op.drop_column('order_date')
        batch_op.drop_column('supply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supply_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_supply_order_ProductID_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'supply', ['supply_id'], ['id'])
        batch_op.drop_column('total_price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('orderDate')
        batch_op.drop_column('ProductID')
        batch_op.drop_column('ID')

    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('manufacturer_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_supply_ManufacturerID_manufacturer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supply_ProductID_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supply_AdminID_admin'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'manufacturer', ['manufacturer_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('ProductID')
        batch_op.drop_column('order_date')
        batch_op.drop_column('quantity_ordered')
        batch_op.drop_column('supply_name')
        batch_op.drop_column('ManufacturerID')
        batch_op.drop_column('AdminID')
        batch_op.drop_column('ID')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_product_supply_id_supply'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_CategoryID_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_manufacturerID_manufacturer'), type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=sa.BigInteger(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('supply_id')
        batch_op.drop_column('ImageURL')
        batch_op.drop_column('manufacturerID')
        batch_op.drop_column('CategoryID')
        batch_op.drop_column('availability')
        batch_op.drop_column('productdescription')
        batch_op.drop_column('Productname')
        batch_op.drop_column('ID')

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Contactinfo')
        batch_op.drop_column('Companyname')
        batch_op.drop_column('Password')
        batch_op.drop_column('Email')
        batch_op.drop_column('Username')
        batch_op.drop_column('ID')

    op.drop_table('sales')
    op.drop_table('receipt')
    op.drop_table('orderdetails')
    op.drop_table('cartitem')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('client')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
