"""Add foreign key to Supply model

Revision ID: 89478569b829
Revises: 
Create Date: 2024-08-09 15:16:49.091751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89478569b829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('category',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('client',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('Shipping_address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('manufacturer',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('Companyname', sa.String(length=128), nullable=True),
    sa.Column('Contactinfo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('cart',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('CreateAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_cart_ClientID_client')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('order',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_order_ClientID_client')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('supply',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_ordered', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.ID'], name=op.f('fk_supply_manufacturer_id_manufacturer')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('product',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Productname', sa.String(length=255), nullable=False),
    sa.Column('productdescription', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('CategoryID', sa.BigInteger(), nullable=False),
    sa.Column('manufacturerID', sa.BigInteger(), nullable=False),
    sa.Column('ImageURL', sa.String(length=255), nullable=True),
    sa.Column('supply_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryID'], ['category.ID'], name=op.f('fk_product_CategoryID_category')),
    sa.ForeignKeyConstraint(['manufacturerID'], ['manufacturer.ID'], name=op.f('fk_product_manufacturerID_manufacturer')),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.ID'], name=op.f('fk_product_supply_id_supply')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('receipt',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('ReceiptDate', sa.DateTime(), nullable=False),
    sa.Column('Total', sa.BigInteger(), nullable=False),
    sa.Column('Payment', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_receipt_ClientID_client')),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], name=op.f('fk_receipt_OrderID_order')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('cartitem',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CartID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CartID'], ['cart.ID'], name=op.f('fk_cartitem_CartID_cart')),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], name=op.f('fk_cartitem_ProductID_product')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('orderdetails',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], name=op.f('fk_orderdetails_OrderID_order')),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], name=op.f('fk_orderdetails_ProductID_product')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('sales',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReceiptID', sa.BigInteger(), nullable=False),
    sa.Column('AdminID', sa.BigInteger(), nullable=False),
    sa.Column('TotalAmount', sa.BigInteger(), nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('Sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.ID'], name=op.f('fk_sales_AdminID_admin')),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], name=op.f('fk_sales_ClientID_client')),
    sa.ForeignKeyConstraint(['ReceiptID'], ['receipt.ID'], name=op.f('fk_sales_ReceiptID_receipt')),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('supply_order',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], name=op.f('fk_supply_order_ProductID_product')),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_order')
    op.drop_table('sales')
    op.drop_table('orderdetails')
    op.drop_table('cartitem')
    op.drop_table('receipt')
    op.drop_table('product')
    op.drop_table('supply')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('manufacturer')
    op.drop_table('client')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
