"""Added Models

Revision ID: ad8bd015986a
Revises: 32973baaee11
Create Date: 2024-08-08 05:36:53.692335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8bd015986a'
down_revision = '32973baaee11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('manufacturer_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_manufacturer_products_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_admin_orders_manufacturer_id_manufacturers')),
    sa.ForeignKeyConstraint(['product_id'], ['manufacturer_products.id'], name=op.f('fk_admin_orders_product_id_manufacturer_products')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_orders')
    op.drop_table('manufacturer_products')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
