"""Added supplies table

Revision ID: e7db5997d2df
Revises: 473b25eb60a7
Create Date: 2024-08-16 02:45:27.648807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7db5997d2df'
down_revision = '473b25eb60a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_ordered', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply')
    # ### end Alembic commands ###
