"""test

Revision ID: 62063025c77a
Revises: 
Create Date: 2024-08-12 10:59:38.984270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62063025c77a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('category',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('client',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('Shipping_address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('manufacturer',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('Companyname', sa.String(length=128), nullable=True),
    sa.Column('Contactinfo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('product',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Productname', sa.String(length=255), nullable=False),
    sa.Column('productdescription', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('CategoryID', sa.BigInteger(), nullable=False),
    sa.Column('manufacturerID', sa.BigInteger(), nullable=False),
    sa.Column('ImageURL', sa.String(length=255), nullable=True),
    sa.Column('supply_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryID'], ['category.ID'], ),
    sa.ForeignKeyConstraint(['manufacturerID'], ['manufacturer.ID'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('supply',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AdminID', sa.BigInteger(), nullable=False),
    sa.Column('ManufacturerID', sa.BigInteger(), nullable=False),
    sa.Column('supply_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_ordered', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['AdminID'], ['admin.ID'], ),
    sa.ForeignKeyConstraint(['ManufacturerID'], ['manufacturer.ID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('cart',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('CreateAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('order',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('supply_order',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('cartitem',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CartID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CartID'], ['cart.ID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('orderdetails',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ProductID', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('receipt',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.BigInteger(), nullable=False),
    sa.Column('ClientID', sa.BigInteger(), nullable=False),
    sa.Column('ReceiptDate', sa.DateTime(), nullable=False),
    sa.Column('Total', sa.BigInteger(), nullable=False),
    sa.Column('Payment', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['client.ID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['order.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.ID'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.ID'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('receipt')
    op.drop_table('orderdetails')
    op.drop_table('cartitem')
    op.drop_table('supply_order')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('supply')
    op.drop_table('product')
    op.drop_table('manufacturer')
    op.drop_table('client')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
